/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rfid.absensikampus.gui;

import services.DigitalClockService;
import javax.swing.SwingUtilities;
import services.SerialService;
import services.MahasiswaServices;
import services.LogAbsensiService;
import objects.Mahasiswa;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Simus
 */

public class DashboardPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardPage.class.getName());
    private final SerialService serialService = SerialService.getInstance();
    private final MahasiswaServices mahasiswaService = new MahasiswaServices();
    private final LogAbsensiService logService = new LogAbsensiService();

    private String lastUID = "";
    private long lastScanTime = 0;

    /**
     * Creates new form DasboardPage
     */
    public DashboardPage(Mahasiswa mahasiswa) {
        initComponents();
        setLocationRelativeTo(null);
        initClock();
        initRFID();
        this.loginMahasiswa = mahasiswa;
        tampilDataMahasiswa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        btnScan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NIM = new javax.swing.JLabel();
        matakuliah = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        lblMataKuliah = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnMenuScan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnScan.setBackground(new java.awt.Color(0, 51, 255));
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });
        jPanel7.add(btnScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, 47));

        jLabel2.setText("Scan Absensi");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        btnReset.setText("Reset Absensi (Testing)");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel7.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 520, 100));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NIM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NIM.setForeground(new java.awt.Color(255, 255, 255));
        NIM.setText("NIM");
        jPanel3.add(NIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, -1));

        matakuliah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        matakuliah.setForeground(new java.awt.Color(255, 255, 255));
        matakuliah.setText("Mata Kuliah");
        jPanel3.add(matakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        lblNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNim.setForeground(new java.awt.Color(255, 255, 255));
        lblNim.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNim.setText("24090077");
        jPanel3.add(lblNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 0, 90, 20));

        lblMataKuliah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMataKuliah.setForeground(new java.awt.Color(255, 255, 255));
        lblMataKuliah.setText("Teknik Informatika");
        jPanel3.add(lblMataKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 520, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selamat Datang");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Arya Ahmad");
        jPanel1.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lblJam.setForeground(new java.awt.Color(255, 255, 255));
        lblJam.setText("08:00");
        jPanel1.add(lblJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 60, 20));

        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("Kamis, 2 Juli 2026");
        jPanel1.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 180));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Status Hari ini");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, -1));

        lblStatus.setBackground(new java.awt.Color(0, 0, 0));
        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 204, 0));
        lblStatus.setText("Hadir");
        jPanel2.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 40));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Keseluruhan");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 190, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 510, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("home");
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        btnMenuScan.setText("Scan");
        btnMenuScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuScanActionPerformed(evt);
            }
        });
        jPanel6.add(btnMenuScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 30));

        jButton3.setText("Riwayat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 30));

        jButton4.setText("Profile");
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 610, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuScanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuScanActionPerformed

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        // TODO add your handling code here:
        String uid = JOptionPane.showInputDialog(
                this,
                "Tempelkan UID RFID",
                "Simulasi RFID",
                JOptionPane.PLAIN_MESSAGE
        );

        if (uid != null && !uid.trim().isEmpty()) {

            processUID(uid.trim());

        }
    }//GEN-LAST:event_btnScanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RiwayatPresensi page =
                new RiwayatPresensi(loginMahasiswa);

        page.setLocationRelativeTo(null);

        page.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(
                this,
                "Hapus seluruh data absensi?",
                "Reset Absensi",
                JOptionPane.YES_NO_OPTION
        );

        if (pilih == JOptionPane.YES_OPTION) {

            long jumlah = logService.resetSemuaAbsensi();

            JOptionPane.showMessageDialog(
                    this,
                    jumlah + " data absensi berhasil dihapus."
            );

        }
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    private void initClock() {

        DigitalClockService clock =
                new DigitalClockService(
                        lblTanggal,
                        lblJam
                );

        clock.getThread().start();
    }
    
    private void initRFID() {

        serialService.addHandler(this::processUID);

    }
    
    private void processUID(String uid) {

        Mahasiswa mahasiswa =
                mahasiswaService.findByUid(uid);

        if (mahasiswa == null) {

            lblNama.setText("-");
            lblNim.setText("-");
            lblMataKuliah.setText("-");
            lblStatus.setText("KARTU TIDAK TERDAFTAR");

            JOptionPane.showMessageDialog(
                    this,
                    "UID tidak ditemukan!"
            );

            return;

        }

        lblNama.setText(mahasiswa.getNamaLengkap());
        lblNim.setText(mahasiswa.getNim());
        lblMataKuliah.setText(mahasiswa.getMataKuliah());
        
        boolean berhasil = logService.simpanAbsensi(mahasiswa);

    if (berhasil) {

        lblStatus.setForeground(new Color(0, 153, 0));
        lblStatus.setText("ABSENSI BERHASIL");

    } else {

        lblStatus.setForeground(Color.ORANGE);
        lblStatus.setText("SUDAH ABSEN HARI INI");

        JOptionPane.showMessageDialog(
                this,
                "Mahasiswa sudah melakukan absensi hari ini."
        );
    }
        
    }
    
    private void tampilDataMahasiswa(){

        lblNama.setText(loginMahasiswa.getNamaLengkap());

        lblNim.setText(loginMahasiswa.getNim());

        lblMataKuliah.setText(
                loginMahasiswa.getMataKuliah()
        );

    }
    
    private Mahasiswa loginMahasiswa;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NIM;
    private javax.swing.JButton btnMenuScan;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnScan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblMataKuliah;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel matakuliah;
    // End of variables declaration//GEN-END:variables
}
