package com.rfid.absensikampus.gui;

import objects.Mahasiswa;
import services.MahasiswaServices;

public class DashboardAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());

    public DashboardAdmin() {
        initComponents();
        
        showData("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     */
    /**
     * Creates new form DashboardAdmin
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NIM = new javax.swing.JTextField();
        NAMALKP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MK = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        data = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MAHASISWA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelola Data Mahasiswa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 630, 43));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UID.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(UID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("UID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("NIM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        NIM.setBackground(new java.awt.Color(204, 204, 204));
        NIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIMActionPerformed(evt);
            }
        });
        jPanel2.add(NIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, -1));

        NAMALKP.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(NAMALKP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("NAMA LENGKAP");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        MK.setBackground(new java.awt.Color(204, 204, 204));
        MK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEMOGRAMAN KOMPUTER", "SISTEM BASIS DATA", "JARINGAN KOMPUTER", "DATA MINING" }));
        MK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKActionPerformed(evt);
            }
        });
        jPanel2.add(MK, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("MATA KULIAH");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        Save.setBackground(new java.awt.Color(51, 51, 255));
        Save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel2.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        update.setBackground(new java.awt.Color(51, 51, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));
        jPanel2.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 630, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIMActionPerformed

    private void MKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MKActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
// TODO add your handling code here:
try {
    Mahasiswa K = new Mahasiswa();
    K.setUid(UID.getText());
    K.setNim(NIM.getText()); 
    K.setNamaLengkap(NAMALKP.getText());
    K.setMataKuliah(MK.getSelectedItem().toString()); 
    
    MahasiswaServices service = new MahasiswaServices();
    System.out.println("SAVE DIKLIK");
    
    // Proses krusial yang rawan terjadi error (DB error, query salah, dll)
    service.tambahMahasiswa(K);
    
    System.out.println("DATA DIKIRIM");
    
    // Refresh tabel/tampilan setelah berhasil simpan
    showData(""); 
    
    // Opsional: Beri tahu user kalau sukses
    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

} catch (Exception e) {
    // Menampilkan pesan error di konsol
    System.err.println("Gagal menyimpan data! Terjadi error:");
    
    // Ini bagian paling penting: mencetak baris kode mana yang rusak dan apa penyebabnya
    e.printStackTrace(); 
    
    // Opsional: Menampilkan pesan error ke user lewat popup
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_SaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        refresAll();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
                                      
    try {
        // 1. Ambil data dari form GUI dan masukkan ke objek Mahasiswa
        Mahasiswa K = new Mahasiswa();
        K.setUid(UID.getText());
        K.setNim(NIM.getText()); 
        K.setNamaLengkap(NAMALKP.getText());
        K.setMataKuliah(MK.getSelectedItem().toString()); 
        
        // 2. Panggil service database
        MahasiswaServices service = new MahasiswaServices();
        
        System.out.println("UPDATE DIKLIK");
        
        // 3. PANGGIL FUNGSI UPDATE (Ganti nama fungsi ini sesuai yang ada di MahasiswaServices Anda)
        service.updateMahasiswa(K); 
        
        System.out.println("DATA DIUPDATE");
        
        // 4. Bersihkan form dan refresh tabel cetak otomatis melalui refresAll()
        refresAll();
        
        // 5. Tampilkan popup sukses ke pengguna
        javax.swing.JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui!");
        
    } catch (Exception e) {
        // Jika terjadi eror (misal koneksi database mati atau error kode bson)
        System.err.println("Gagal mengupdate data! Terjadi error:");
        e.printStackTrace(); // Mencetak baris error di konsol NetBeans
        
        // Menampilkan pesan error berupa popup
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> MK;
    public static javax.swing.JTextField NAMALKP;
    public static javax.swing.JTextField NIM;
    public static javax.swing.JButton Save;
    public static javax.swing.JTextField UID;
    private static javax.swing.JPanel data;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    public static void showData(String key) {
        MahasiswaServices K = new MahasiswaServices();
        K.tampilMahasiswa(data, key);
    }

    private void refresAll() {
        showData("");
        UID.setText("");
        NIM.setText("");
        NAMALKP.setText("");
        MK.setSelectedIndex(0); 
        update.setEnabled(false); 
        UID.requestFocus();
    }

    public static class uid {

        public static void setText(String uid) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public uid() {
        }
    }

    public static class MK {

        public static void setSelectedItem(String mataKuliah) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public MK() {
        }
    }

    public static class Update {

        public Update() {
        }
    }
    
}


